package com.example.ktorservice.codegen

import com.squareup.kotlinpoet.BOOLEAN
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.MAP
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.SET
import com.squareup.kotlinpoet.STAR
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeSpec
import io.github.ehlyzov.branchline.contract.TransformContract
import java.nio.file.Files
import java.nio.file.Path

data class GeneratedTransformDescriptor(
    val transformName: String,
    val inputClassName: ClassName,
    val outputClassName: ClassName,
    val inputOpen: Boolean,
    val outputMayEmitNull: Boolean,
)

class KotlinPoetDtoGenerator {
    fun generate(
        contracts: Map<String, TransformContract>,
        outputDir: Path,
        packageName: String,
    ) {
        resetOutputDir(outputDir)
        val mapper = ContractTypeMapper(packageName)
        val descriptors = mutableListOf<GeneratedTransformDescriptor>()

        for ((transformName, contract) in contracts.toSortedMap()) {
            val inputSpec = mapper.createRootDto(transformName, "InputDto", contract.input.root)
            val outputSpec = mapper.createRootDto(transformName, "OutputDto", contract.output.root)
            writeTransformFile(
                outputDir = outputDir,
                packageName = packageName,
                transformName = transformName,
                inputSpec = inputSpec,
                outputSpec = outputSpec,
            )
            descriptors += GeneratedTransformDescriptor(
                transformName = transformName,
                inputClassName = inputSpec.rootClassName,
                outputClassName = outputSpec.rootClassName,
                inputOpen = contract.input.root.open,
                outputMayEmitNull = contract.output.mayEmitNull,
            )
        }

        writeIndexFile(outputDir, packageName, descriptors)
    }

    private fun resetOutputDir(outputDir: Path) {
        if (Files.exists(outputDir)) {
            outputDir.toFile().deleteRecursively()
        }
        Files.createDirectories(outputDir)
    }

    private fun writeTransformFile(
        outputDir: Path,
        packageName: String,
        transformName: String,
        inputSpec: GeneratedDtoSpec,
        outputSpec: GeneratedDtoSpec,
    ) {
        val fileName = sanitizeTypeName(transformName) + "ContractsDtos"
        val uniqueTypes = LinkedHashMap<String, TypeSpec>()
        for (type in inputSpec.typeSpecs) {
            uniqueTypes[type.name!!] = type
        }
        for (type in outputSpec.typeSpecs) {
            uniqueTypes[type.name!!] = type
        }

        val fileBuilder = FileSpec.builder(packageName, fileName)
            .addFileComment("Generated by KotlinPoet from Branchline contracts. Do not edit manually.")

        for (type in uniqueTypes.values) {
            fileBuilder.addType(type)
        }

        fileBuilder.build().writeTo(outputDir)
    }

    private fun writeIndexFile(
        outputDir: Path,
        packageName: String,
        descriptors: List<GeneratedTransformDescriptor>,
    ) {
        val kClassType = ClassName("kotlin.reflect", "KClass").parameterizedBy(STAR)
        val mapStringToKClass = MAP.parameterizedBy(STRING, kClassType)
        val mapStringToBoolean = MAP.parameterizedBy(STRING, BOOLEAN)

        val indexType = TypeSpec.objectBuilder("GeneratedContractsIndex")
            .addKdoc("Maps transform names to generated DTO metadata.")
            .addProperty(
                PropertySpec.builder("transforms", SET.parameterizedBy(STRING))
                    .initializer(buildSetCode(descriptors))
                    .build(),
            )
            .addProperty(
                PropertySpec.builder("inputDtoByTransform", mapStringToKClass)
                    .initializer(buildInputMapCode(descriptors))
                    .build(),
            )
            .addProperty(
                PropertySpec.builder("outputDtoByTransform", mapStringToKClass)
                    .initializer(buildOutputMapCode(descriptors))
                    .build(),
            )
            .addProperty(
                PropertySpec.builder("inputOpenByTransform", mapStringToBoolean)
                    .initializer(buildInputOpenMapCode(descriptors))
                    .build(),
            )
            .addProperty(
                PropertySpec.builder("outputMayEmitNullByTransform", mapStringToBoolean)
                    .initializer(buildOutputMayEmitNullMapCode(descriptors))
                    .build(),
            )
            .build()

        FileSpec.builder(packageName, "GeneratedContractsIndex")
            .addFileComment("Generated by KotlinPoet from Branchline contracts. Do not edit manually.")
            .addType(indexType)
            .build()
            .writeTo(outputDir)
    }

    private fun buildSetCode(descriptors: List<GeneratedTransformDescriptor>): CodeBlock {
        val builder = CodeBlock.builder()
        builder.add("setOf(\n")
        for (descriptor in descriptors) {
            builder.add("    %S,\n", descriptor.transformName)
        }
        builder.add(")")
        return builder.build()
    }

    private fun buildInputMapCode(descriptors: List<GeneratedTransformDescriptor>): CodeBlock {
        val builder = CodeBlock.builder()
        builder.add("mapOf(\n")
        for (descriptor in descriptors) {
            builder.add(
                "    %S to %T::class,\n",
                descriptor.transformName,
                descriptor.inputClassName,
            )
        }
        builder.add(")")
        return builder.build()
    }

    private fun buildOutputMapCode(descriptors: List<GeneratedTransformDescriptor>): CodeBlock {
        val builder = CodeBlock.builder()
        builder.add("mapOf(\n")
        for (descriptor in descriptors) {
            builder.add(
                "    %S to %T::class,\n",
                descriptor.transformName,
                descriptor.outputClassName,
            )
        }
        builder.add(")")
        return builder.build()
    }

    private fun buildInputOpenMapCode(descriptors: List<GeneratedTransformDescriptor>): CodeBlock {
        val builder = CodeBlock.builder()
        builder.add("mapOf(\n")
        for (descriptor in descriptors) {
            builder.add(
                "    %S to %L,\n",
                descriptor.transformName,
                descriptor.inputOpen,
            )
        }
        builder.add(")")
        return builder.build()
    }

    private fun buildOutputMayEmitNullMapCode(descriptors: List<GeneratedTransformDescriptor>): CodeBlock {
        val builder = CodeBlock.builder()
        builder.add("mapOf(\n")
        for (descriptor in descriptors) {
            builder.add(
                "    %S to %L,\n",
                descriptor.transformName,
                descriptor.outputMayEmitNull,
            )
        }
        builder.add(")")
        return builder.build()
    }

    private fun sanitizeTypeName(raw: String): String {
        val buffer = StringBuilder()
        var nextUpper = true
        for (char in raw) {
            if (!char.isLetterOrDigit()) {
                nextUpper = true
                continue
            }
            if (nextUpper) {
                buffer.append(char.uppercaseChar())
                nextUpper = false
            } else {
                buffer.append(char)
            }
        }
        val candidate = if (buffer.isEmpty()) "Generated" else buffer.toString()
        return if (candidate.firstOrNull()?.isDigit() == true) "T$candidate" else candidate
    }
}
