package v2.vm

enum class Opcode {
    PUSH, DUP, POP, SWAP,
    LOAD_VAR, STORE_VAR, LOAD_SCOPE, LOAD_LOCAL, STORE_LOCAL,
    ADD, SUB, MUL, DIV, MOD, NEG,
    EQ, NEQ, LT, LE, GT, GE,
    AND, OR, NOT, COALESCE,
    MAKE_OBJECT, MAKE_ARRAY, ACCESS_STATIC, ACCESS_DYNAMIC,
    SET_STATIC, SET_DYNAMIC, APPEND, CONCAT,
    JUMP, JUMP_IF_TRUE, JUMP_IF_FALSE, JUMP_IF_NULL,
    CALL, CALL_HOST, CALL_FN, CALL_LAMBDA, RETURN, RETURN_VALUE,
    OUTPUT, MODIFY, INIT_FOREACH, NEXT_FOREACH,
    TRY_START, TRY_END, CATCH, ABORT,
    TRACE, BREAKPOINT, LINE, NOP,
    SUSPEND
}

