package v2

import kotlinx.serialization.Serializable

@Serializable
enum class TokenType {
    // Single-character tokens
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    LEFT_BRACKET, RIGHT_BRACKET, COMMA, DOT, SEMICOLON, COLON,
    QUESTION, PLUS, MINUS, STAR, SLASH, PERCENT,
    LT, GT, ASSIGN, BANG, SET, APPEND, TO, INIT,

    // One- or two-character tokens
    LE, GE, EQ, NEQ, ARROW, AND, OR, COALESCE,

    // Literals
    IDENTIFIER, STRING, NUMBER,

    // Keywords
    SOURCE, OUTPUT, USING, TRANSFORM, STREAM, BUFFER,
    FOR, EACH, CASE, WHEN, IF, THEN, ELSE, AS, ENUM, LET, IN,
    AWAIT, SUSPEND, CALL, TRUE, FALSE, NULL,
    PARALLEL, ONBLOCK, FOREACH, INPUT, PIPE,
    ABORT, THROW, TRY, CATCH, RETRY, TIMES, BACKOFF,
    SHARED, SINGLE, MANY, FUNC, TYPE, RETURN,
    UNION, DOLLAR, MODIFY, CONCAT, WHERE,

    // End of file
    EOF
}
